<a href="javascript:insert(':angry:')"><span class='emoji emoji1f620'></span></a>
<a href="javascript:insert(':((')"><span class='emoji emoji1f629'></span></a>
<a href="javascript:insert('x_x')"><span class='emoji emoji1f632'></span></a>
<a href="javascript:insert('-_-')"><span class='emoji emoji1f61e'></span></a>
<a href="javascript:insert(':O')"><span class='emoji emoji1f635'></span></a>
<a href="javascript:insert(':hah:')"><span class='emoji emoji1f630'></span></a>
<a href="javascript:insert(':bzzz:')"><span class='emoji emoji1f612'></span></a>
<a href="javascript:insert(':love:')"><span class='emoji emoji1f60d'></span></a>
<a href="javascript:insert(':huh:')"><span class='emoji emoji1f624'></span></a>
<a href="javascript:insert(';P')"><span class='emoji emoji1f61c'></span></a>
<a href="javascript:insert(':P')"><span class='emoji emoji1f61d'></span></a>
<a href="javascript:insert(':))')"><span class='emoji emoji1f60b'></span></a>
<a href="javascript:insert(':kiss:')"><span class='emoji emoji1f618'></span></a>
<a href="javascript:insert(':*')"><span class='emoji emoji1f61a'></span></a>
<a href="javascript:insert(':x')"><span class='emoji emoji1f637'></span></a>
<a href="javascript:insert('O.O')"><span class='emoji emoji1f633'></span></a>
<a href="javascript:insert(':D')"><span class='emoji emoji1f603'></span></a>
<a href="javascript:insert(':hehe:')"><span class='emoji emoji1f605'></span></a>
<a href="javascript:insert(':haha:')"><span class='emoji emoji1f606'></span></a>
<a href="javascript:insert('^_^')"><span class='emoji emoji1f601'></span></a>
<a href="javascript:insert(':ahik:')"><span class='emoji emoji1f602'></span></a>
<a href="javascript:insert(':)')"><span class='emoji emoji1f60a'></span></a>
<a href="javascript:insert(':smallsmile:')"><span class='emoji emoji263a'></span></a>
<a href="javascript:insert(':laugh:')"><span class='emoji emoji1f604'></span></a>
<a href="javascript:insert(':sad:')"><span class='emoji emoji1f622'></span></a>
<a href="javascript:insert('T_T')"><span class='emoji emoji1f62d'></span></a>
<a href="javascript:insert(':shock:')"><span class='emoji emoji1f628'></span></a>
<a href="javascript:insert('>..<')"><span class='emoji emoji1f623'></span></a>
<a href="javascript:insert(':veryangry:')"><span class='emoji emoji1f621'></span></a>
<a href="javascript:insert(':yahh:')"><span class='emoji emoji1f60c'></span></a>
<a href="javascript:insert(':uhh:')"><span class='emoji emoji1f616'></span></a>
<a href="javascript:insert(':.pessimist:')"><span class='emoji emoji1f614'></span></a>
<a href="javascript:insert(':scream:')"><span class='emoji emoji1f631'></span></a>
<a href="javascript:insert(':sleapy:')"><span class='emoji emoji1f62a'></span></a>
<a href="javascript:insert(':smirking:')"><span class='emoji emoji1f60f'></span></a>
<a href="javascript:insert(':jiah:')"><span class='emoji emoji1f613'></span></a>
<a href="javascript:insert(':disappointed:')"><span class='emoji emoji1f625'></span></a>
<a href="javascript:insert('l_l')"><span class='emoji emoji1f62b'></span></a>
<a href="javascript:insert(';)')"><span class='emoji emoji1f609'></span></a>