#!/bin/bash

# Refer to https://blog.tommyku.com/blog/setting-up-laravel-5-0-for-openshift

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

# Make sure Composer is installed

if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
        echo 'Installing Composer'
        curl -s https://getcomposer.org/installer | php -- --quiet --install-dir=$OPENSHIFT_DATA_DIR
else
        echo 'Updating Composer'
        php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi self-update
fi

# Install app dependencies

if [ -d "$OPENSHIFT_REPO_DIR/vendor" ]; then
        echo 'Dependencies already installed, Moving on...'
else
        echo 'Hang in there, we are getting ready to Install/update dependencies'
        echo 'Installing/updating dependencies'; 
        unset GIT_DIR ; 
        cd $OPENSHIFT_REPO_DIR ; 
        php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi install ;
fi

# Replace storage directory with a link to a storage directory in the Openshift data directory

if [ ! -d "$OPENSHIFT_DATA_DIR/storage" ]; then
        echo 'No existing storage found'
        echo 'Copying storage directory from application repository storage directory'
        cp -r --preserve "OPENSHIFT_REPO_DIR/storage" $OPENSHIFT_DATA_DIR
fi

echo 'Deleting existing application storage directory in application repository'
rm -rf "$OPENSHIFT_REPO_DIR/storage"

echo 'Linking storage to Openshift data directory'
ln -s $OPENSHIFT_DATA_DIR/storage "$OPENSHIFT_REPO_DIR/storage"